library("RJSONIO")
filename = "20150208"
readjson <- function(filename){
  s <- fromJSON(filename)
 
  return (s)
}

dailySummary <- function(filename){
  output <- readjson(filename)
  writeLines(paste("Date =======> ",output$history$dailysummary[[1]]$date$pretty))
  writeLines(paste("TimeZone ====> ",output$history$dailysummary[[1]]$date$tzname))
  writeLines(paste("Fog ========>",output$history$dailysummary[[1]]$fog))
  writeLines(paste("Rain =========> ",output$history$dailysummary[[1]]$rain))
  writeLines(paste("SnowFall =========> ",output$history$dailysummary[[1]]$snow))
  writeLines(paste("SnowFall(m) =========> ",output$history$dailysummary[[1]]$snowfallm))
  writeLines(paste("SnowFall(i) =========> ",output$history$dailysummary[[1]]$snowfalli))
  writeLines(paste("Month to date snowfall(m) =========> ",output$history$dailysummary[[1]]$monthtodatesnowfallm))
  writeLines(paste("Month to date snowfall(i) =========> ",output$history$dailysummary[[1]]$monthtodatesnowfalli))
  writeLines(paste("Since 1st July SnowFall(m)=========> ",output$history$dailysummary[[1]]$since1julsnowfallm))
  writeLines(paste("Since 1st July SnowFall(i)=========> ",output$history$dailysummary[[1]]$since1julsnowfalli))
  writeLines(paste("Snow Depth(m) =========> ",output$history$dailysummary[[1]]$snowdepthm))
  writeLines(paste("Snow Depth(i) =========> ",output$history$dailysummary[[1]]$snowdepthi))
  writeLines(paste("Hail =========> ",output$history$dailysummary[[1]]$hail))
  writeLines(paste("Thunder =========> ",output$history$dailysummary[[1]]$thunder))
  writeLines(paste("Tornado =========> ",output$history$dailysummary[[1]]$tornado))
  writeLines(paste("Mean Temp(C) =========> ",output$history$dailysummary[[1]]$meantempm))
  writeLines(paste("Mean Temp(F) =========> ",output$history$dailysummary[[1]]$meantempi))
  writeLines(paste("Mean Dew Point(m) =========> ",output$history$dailysummary[[1]]$meandewptm))
  writeLines(paste("Mean Dew Point(i) =========> ",output$history$dailysummary[[1]]$meandewpti))
  writeLines(paste("Mean pressure(m) =========> ",output$history$dailysummary[[1]]$meanpressurem))
  writeLines(paste("Mean pressure(i) =========> ",output$history$dailysummary[[1]]$meanpressurei))
  writeLines(paste("Mean Wind Speed(m) =========> ",output$history$dailysummary[[1]]$meanwindspdm))
  writeLines(paste("Mean Wind Speed(i) =========> ",output$history$dailysummary[[1]]$meanwindspdi))
  writeLines(paste("Mean Wind Direction(e) =========> ",output$history$dailysummary[[1]]$meanwdire))
  writeLines(paste("Mean Wind Direction(d) =========> ",output$history$dailysummary[[1]]$meanwdird))
  writeLines(paste("Mean Vision(m) =========> ",output$history$dailysummary[[1]]$meanvism))
  writeLines(paste("Mean Vision(i) =========> ",output$history$dailysummary[[1]]$meanvisi))
  writeLines(paste("Humidity =========> ",output$history$dailysummary[[1]]$humidity))
  writeLines(paste("Max Temp(m) =========> ",output$history$dailysummary[[1]]$maxtempm))
  writeLines(paste("Max Temp(i) =========> ",output$history$dailysummary[[1]]$maxtempi))
  writeLines(paste("Min Temp(m) =========> ",output$history$dailysummary[[1]]$mintempm))
  writeLines(paste("Min Temp(i) =========> ",output$history$dailysummary[[1]]$mintempi))
  writeLines(paste("Max Humidity =========> ",output$history$dailysummary[[1]]$maxhumidity))
  writeLines(paste("Min Humidity =========> ",output$history$dailysummary[[1]]$minhumidity))
  writeLines(paste("Max Dew Point(m) =========> ",output$history$dailysummary[[1]]$maxdewptm))
  writeLines(paste("Max Dew Point(i) =========> ",output$history$dailysummary[[1]]$maxdewpti))
  writeLines(paste("Max Pressure(m) =========> ",output$history$dailysummary[[1]]$maxpressurem))
  writeLines(paste("Max Pressure(i) =========> ",output$history$dailysummary[[1]]$maxpressurei))
  writeLines(paste("Min Pressure(m) =========> ",output$history$dailysummary[[1]]$minpressurem))
  writeLines(paste("Min Pressure(i) =========> ",output$history$dailysummary[[1]]$minpressurei))
  writeLines(paste("Max Wind Speed(m) =========> ",output$history$dailysummary[[1]]$maxwspdm))
  writeLines(paste("Max Wind Speed(i) =========> ",output$history$dailysummary[[1]]$maxwspdi))
  writeLines(paste("Min Wind Speed(m) =========> ",output$history$dailysummary[[1]]$minwspdm))
  writeLines(paste("Min Wind Speed(i) =========> ",output$history$dailysummary[[1]]$minwspdi))
  writeLines(paste("Max Visibility(m) =========> ",output$history$dailysummary[[1]]$maxvism))
  writeLines(paste("Max Visibility(i) =========> ",output$history$dailysummary[[1]]$maxvisi))
  writeLines(paste("Min Visibility(m) =========> ",output$history$dailysummary[[1]]$minvism))
  writeLines(paste("Min Visibility(i) =========> ",output$history$dailysummary[[1]]$minvisi))
  writeLines(paste("GDegree Days =========> ",output$history$dailysummary[[1]]$gdegreedays))
  writeLines(paste("Heating degree Days =========> ",output$history$dailysummary[[1]]$heatingdegreedays))
  writeLines(paste("Cooling Degree Days =========> ",output$history$dailysummary[[1]]$coolingdegreedays))
  writeLines(paste("Precipitation(m) =========> ",output$history$dailysummary[[1]]$precipm))
  writeLines(paste("Precipitation(i)) =========> ",output$history$dailysummary[[1]]$precipi))
  writeLines(paste("Precipitation source =========> ",output$history$dailysummary[[1]]$precipsource))
  writeLines(paste("Heating Degree Days Normal =========> ",output$history$dailysummary[[1]]$heatingdegreedaysnormal))
  writeLines(paste("Month-to-date Heating Degree Days =========> ",output$history$dailysummary[[1]]$monthtodateheatingdegreedays))
  writeLines(paste("Since 1st September Heating Degree Days =========> ",output$history$dailysummary[[1]]$since1sepheatingdegreedays))
  writeLines(paste("Since 1st September Heating Degree Days Normal=========> ",output$history$dailysummary[[1]]$since1sepheatingdegreedaysnormal))
  writeLines(paste("Since 1st July Heating Degree Days =========> ",output$history$dailysummary[[1]]$since1julheatingdegreedays))
  writeLines(paste("Since 1st July Heating Degree Days Normal=========> ",output$history$dailysummary[[1]]$since1julheatingdegreedaysnormal))
  writeLines(paste("Cooling Degree Days Normal =========> ",output$history$dailysummary[[1]]$coolingdegreedaysnormal))
  writeLines(paste("Month-to-date Cooling Degree Days =========> ",output$history$dailysummary[[1]]$monthtodatecoolingdegreedays))
  writeLines(paste("Month-to-date Cooling Degree Days Normal =========> ",output$history$dailysummary[[1]]$monthtodatecoolingdegreedaysnormal))
  writeLines(paste("Since 1st September Cooling Degree Days =========> ",output$history$dailysummary[[1]]$since1sepcoolingdegreedays))
  writeLines(paste("Since 1st September CoolingDegree Days Normal=========> ",output$history$dailysummary[[1]]$since1sepcoolingdegreedaysnormal))
  writeLines(paste("Since 1st Jan Cooling Degree Days =========> ",output$history$dailysummary[[1]]$since1jancoolingdegreedays))
  writeLines(paste("Since 1st Jan Cooling Degree Days Normal=========> ",output$history$dailysummary[[1]]$since1jancoolingdegreedaysnormal))
}

